// TYPE PRODUCT
export const Get_DATA_PRODUCT = Symbol("GET_DATA_PRODUCT");
export const START_GET_DATA_PRODUCT = Symbol("START_GET_DATA_PRODUCT");
export const GET_DATA_SUCESS = Symbol("GET_DATA_SUCESS");
export const GET_DATA_FAIL = Symbol("GET_DATA_FAIL");
export const STOP_GET_DATA_PRODUCT = Symbol("STOP_GET_DATA_PRODUCT");
export const NOT_FOUND_DATA_PRODUCT = Symbol("NOT_FOUND_DATA_PRODUCT");

// TYPE DETAIL
export const GET_DATA_PRODUCT_BY_ID = Symbol("GET_DATA_PRODUCT_BY_ID");
// SAGAS DETAIL
export const START_GET_DATA_PRODUCT_BY_ID = Symbol(
  "START_GET_DATA_PRODUCT_BY_ID"
);
export const GET_DATA_SUCESS_BY_ID = Symbol("GET_DATA_SUCESS_BY_ID");
export const GET_DATA_FAIL_BY_ID = Symbol("GET_DATA_FAIL_BY_ID");
export const STOP_GET_DATA_PRODUCT_BY_ID = Symbol(
  "STOP_GET_DATA_PRODUCT_BY_ID"
);
export const NOT_FOUND_DATA_PRODUCT_BY_ID = Symbol(
  "NOT_FOUND_DATA_PRODUCT_BY_ID"
);
